export interface Employee {
  id: string
  name: string
  position: string
  department: string
  leader: string
  oneOnOnePerson: string
  meetingDate: string
  monthYear: string
  status: string
  workload: string
  comment: string
}

export const employees: Employee[] = [
  {
    id: "1",
    name: "Alex Johnson",
    position: "Senior Designer",
    department: "Design",
    leader: "Sarah Williams",
    oneOnOnePerson: "Sarah Williams",
    meetingDate: "2025-06-15",
    monthYear: "June 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Alex is performing well and meeting all deadlines. Discussed career growth opportunities.",
  },
  {
    id: "2",
    name: "Jamie Smith",
    position: "UX Designer",
    department: "Design",
    leader: "Sarah Williams",
    oneOnOnePerson: "Sarah Williams",
    meetingDate: "2025-06-10",
    monthYear: "June 2025",
    status: "🟨 Yellow",
    workload: "Overloaded",
    comment: "Jamie is feeling overwhelmed with current project load. Need to reassess workload distribution.",
  },
  {
    id: "3",
    name: "Taylor Brown",
    position: "Product Manager",
    department: "Product",
    leader: "Michael Chen",
    oneOnOnePerson: "Michael Chen",
    meetingDate: "2025-06-08",
    monthYear: "June 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Taylor is excelling in leading the new product initiative. Team feedback is very positive.",
  },
  {
    id: "4",
    name: "Morgan Lee",
    position: "Sales Representative",
    department: "Sales",
    leader: "Robert Garcia",
    oneOnOnePerson: "Robert Garcia",
    meetingDate: "2025-06-05",
    monthYear: "June 2025",
    status: "🟥 Red",
    workload: "Low",
    comment: "Morgan is struggling to meet sales targets. Implementing a performance improvement plan.",
  },
  {
    id: "5",
    name: "Casey Wilson",
    position: "Marketing Specialist",
    department: "Marketing",
    leader: "Emma Davis",
    oneOnOnePerson: "Emma Davis",
    meetingDate: "2025-06-03",
    monthYear: "June 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Casey's recent campaign exceeded expectations. Discussing potential for team lead role.",
  },
  {
    id: "6",
    name: "Jordan Miller",
    position: "Financial Analyst",
    department: "Finance",
    leader: "David Thompson",
    oneOnOnePerson: "David Thompson",
    meetingDate: "2025-05-28",
    monthYear: "May 2025",
    status: "🟨 Yellow",
    workload: "Overloaded",
    comment: "Jordan needs additional support during the quarterly reporting period.",
  },
  {
    id: "7",
    name: "Riley Cooper",
    position: "HR Specialist",
    department: "Talent Management",
    leader: "Patricia Martinez",
    oneOnOnePerson: "Patricia Martinez",
    meetingDate: "2025-05-25",
    monthYear: "May 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Riley is doing an excellent job with the new employee onboarding process.",
  },
  {
    id: "8",
    name: "Avery Thomas",
    position: "UI Designer",
    department: "Design",
    leader: "Sarah Williams",
    oneOnOnePerson: "Sarah Williams",
    meetingDate: "2025-05-20",
    monthYear: "May 2025",
    status: "🟥 Red",
    workload: "Overloaded",
    comment: "Avery is having difficulty adapting to the new design system. Providing additional training.",
  },
  {
    id: "9",
    name: "Quinn Adams",
    position: "Product Designer",
    department: "Product",
    leader: "Michael Chen",
    oneOnOnePerson: "Michael Chen",
    meetingDate: "2025-05-18",
    monthYear: "May 2025",
    status: "🟩 Green",
    workload: "Low",
    comment: "Quinn has capacity to take on additional projects. Discussing new opportunities.",
  },
  {
    id: "10",
    name: "Reese Campbell",
    position: "Account Manager",
    department: "Sales",
    leader: "Robert Garcia",
    oneOnOnePerson: "Robert Garcia",
    meetingDate: "2025-05-15",
    monthYear: "May 2025",
    status: "🟨 Yellow",
    workload: "Balanced",
    comment: "Reese is managing key accounts well but needs support with client communication strategies.",
  },
  {
    id: "11",
    name: "Drew Parker",
    position: "Content Strategist",
    department: "Marketing",
    leader: "Emma Davis",
    oneOnOnePerson: "Emma Davis",
    meetingDate: "2025-05-12",
    monthYear: "May 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Drew's content strategy has significantly improved engagement metrics.",
  },
  {
    id: "12",
    name: "Blake Evans",
    position: "Budget Analyst",
    department: "Finance",
    leader: "David Thompson",
    oneOnOnePerson: "David Thompson",
    meetingDate: "2025-05-10",
    monthYear: "May 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Blake has streamlined the budget review process, saving significant time.",
  },
  {
    id: "13",
    name: "Cameron Wright",
    position: "Talent Acquisition",
    department: "Talent Management",
    leader: "Patricia Martinez",
    oneOnOnePerson: "Patricia Martinez",
    meetingDate: "2025-05-08",
    monthYear: "May 2025",
    status: "🟨 Yellow",
    workload: "Overloaded",
    comment: "Cameron is handling multiple open positions. Need to prioritize hiring efforts.",
  },
  {
    id: "14",
    name: "Skyler King",
    position: "Motion Designer",
    department: "Design",
    leader: "Sarah Williams",
    oneOnOnePerson: "Sarah Williams",
    meetingDate: "2025-05-05",
    monthYear: "May 2025",
    status: "🟩 Green",
    workload: "Balanced",
    comment: "Skyler's animations have received excellent client feedback.",
  },
  {
    id: "15",
    name: "Hayden Scott",
    position: "Product Analyst",
    department: "Product",
    leader: "Michael Chen",
    oneOnOnePerson: "Michael Chen",
    meetingDate: "2025-05-03",
    monthYear: "May 2025",
    status: "🟥 Red",
    workload: "Balanced",
    comment: "Hayden is struggling with data analysis tasks. Arranging additional training.",
  },
]
